export const sampleData = {
  project_id: "proj-001",
  project_name: "ACME Internal Assessment",
  description: "Internal pentest of ACME Corp's HQ LAN and DMZ",
  date_started: "2025-05-01T08:00:00Z",
  date_completed: null,
  created_by: "ryan",
  networks: [
    {
      network_id: "net-001",
      name: "Internal LAN",
      cidr_block: "10.0.0.0/24",
      notes:
        "Corporate internal network with DC, file shares, and user workstations",
    },
    {
      network_id: "net-002",
      name: "DMZ",
      cidr_block: "192.168.1.0/24",
      notes: "DMZ network with public-facing services",
    },
  ],
  hosts: [
    {
      host_id: "host-003",
      ip_address: "10.0.0.101",
      hostname: "Internal-host-1",
      os: "Windows 10 Pro",
      status: "vulnerable",
      first_seen: "2025-05-09T09:40:00Z",
      last_updated: "2025-05-03T20:21:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-004",
      ip_address: "10.0.0.66",
      hostname: "Internal-host-2",
      os: "Windows Server 2019",
      status: "exploited",
      first_seen: "2025-05-08T10:35:00Z",
      last_updated: "2025-05-04T22:52:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-005",
      ip_address: "10.0.0.229",
      hostname: "Internal-host-3",
      os: "Windows Server 2019",
      status: "discovered",
      first_seen: "2025-05-08T05:33:00Z",
      last_updated: "2025-05-06T22:54:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-006",
      ip_address: "10.0.0.213",
      hostname: "Internal-host-4",
      os: "Windows 10 Pro",
      status: "discovered",
      first_seen: "2025-05-12T01:36:00Z",
      last_updated: "2025-05-06T05:47:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-007",
      ip_address: "10.0.0.32",
      hostname: "Internal-host-5",
      os: "Windows Server 2019",
      status: "enumerated",
      first_seen: "2025-05-10T12:42:00Z",
      last_updated: "2025-05-07T02:43:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-008",
      ip_address: "10.0.0.245",
      hostname: "Internal-host-6",
      os: "Windows 10 Pro",
      status: "discovered",
      first_seen: "2025-05-04T06:51:00Z",
      last_updated: "2025-05-05T08:59:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-009",
      ip_address: "10.0.0.99",
      hostname: "Internal-host-7",
      os: "Ubuntu 20.04",
      status: "exploited",
      first_seen: "2025-05-03T23:29:00Z",
      last_updated: "2025-05-06T12:45:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-010",
      ip_address: "10.0.0.239",
      hostname: "Internal-host-8",
      os: "Ubuntu 20.04",
      status: "exploited",
      first_seen: "2025-05-05T23:35:00Z",
      last_updated: "2025-05-07T20:02:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-011",
      ip_address: "10.0.0.43",
      hostname: "Internal-host-9",
      os: "Ubuntu 20.04",
      status: "exploited",
      first_seen: "2025-05-08T09:56:00Z",
      last_updated: "2025-05-03T15:27:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-012",
      ip_address: "10.0.0.70",
      hostname: "Internal-host-10",
      os: "Windows Server 2019",
      status: "enumerated",
      first_seen: "2025-05-06T11:41:00Z",
      last_updated: "2025-05-01T08:01:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-013",
      ip_address: "10.0.0.164",
      hostname: "Internal-host-11",
      os: "Ubuntu 20.04",
      status: "vulnerable",
      first_seen: "2025-05-11T20:27:00Z",
      last_updated: "2025-05-09T05:17:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-014",
      ip_address: "10.0.0.137",
      hostname: "Internal-host-12",
      os: "Windows 10 Pro",
      status: "vulnerable",
      first_seen: "2025-05-09T11:46:00Z",
      last_updated: "2025-05-06T03:08:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-015",
      ip_address: "10.0.0.10",
      hostname: "Internal-host-13",
      os: "Windows Server 2019",
      status: "discovered",
      first_seen: "2025-05-10T18:25:00Z",
      last_updated: "2025-05-07T14:15:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-016",
      ip_address: "10.0.0.230",
      hostname: "Internal-host-14",
      os: "Ubuntu 20.04",
      status: "vulnerable",
      first_seen: "2025-05-02T14:41:00Z",
      last_updated: "2025-05-02T14:49:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-017",
      ip_address: "10.0.0.119",
      hostname: "Internal-host-15",
      os: "Windows 10 Pro",
      status: "enumerated",
      first_seen: "2025-05-04T20:39:00Z",
      last_updated: "2025-05-12T03:07:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-018",
      ip_address: "10.0.0.6",
      hostname: "Internal-host-16",
      os: "Windows Server 2019",
      status: "exploited",
      first_seen: "2025-05-08T17:53:00Z",
      last_updated: "2025-05-11T13:07:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-019",
      ip_address: "10.0.0.139",
      hostname: "Internal-host-17",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-09T12:55:00Z",
      last_updated: "2025-05-04T04:39:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-020",
      ip_address: "10.0.0.123",
      hostname: "Internal-host-18",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-12T07:54:00Z",
      last_updated: "2025-05-03T05:30:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-021",
      ip_address: "10.0.0.74",
      hostname: "Internal-host-19",
      os: "Windows 10 Pro",
      status: "enumerated",
      first_seen: "2025-05-11T23:20:00Z",
      last_updated: "2025-05-11T23:25:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-022",
      ip_address: "10.0.0.142",
      hostname: "Internal-host-20",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-07T03:07:00Z",
      last_updated: "2025-05-08T04:51:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-023",
      ip_address: "10.0.0.135",
      hostname: "Internal-host-21",
      os: "CentOS 7",
      status: "exploited",
      first_seen: "2025-05-02T11:07:00Z",
      last_updated: "2025-05-08T15:38:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-024",
      ip_address: "10.0.0.176",
      hostname: "Internal-host-22",
      os: "Windows Server 2019",
      status: "enumerated",
      first_seen: "2025-05-10T01:59:00Z",
      last_updated: "2025-05-12T04:57:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-025",
      ip_address: "10.0.0.59",
      hostname: "Internal-host-23",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-10T07:26:00Z",
      last_updated: "2025-05-10T09:02:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-026",
      ip_address: "10.0.0.79",
      hostname: "Internal-host-24",
      os: "Windows Server 2019",
      status: "discovered",
      first_seen: "2025-05-04T01:45:00Z",
      last_updated: "2025-05-01T13:22:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-027",
      ip_address: "10.0.0.166",
      hostname: "Internal-host-25",
      os: "Windows Server 2019",
      status: "exploited",
      first_seen: "2025-05-09T15:23:00Z",
      last_updated: "2025-05-06T04:28:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-028",
      ip_address: "10.0.0.71",
      hostname: "Internal-host-26",
      os: "Ubuntu 20.04",
      status: "discovered",
      first_seen: "2025-05-03T05:38:00Z",
      last_updated: "2025-05-06T01:46:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-029",
      ip_address: "10.0.0.14",
      hostname: "Internal-host-27",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-10T18:02:00Z",
      last_updated: "2025-05-02T14:13:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-030",
      ip_address: "10.0.0.159",
      hostname: "Internal-host-28",
      os: "CentOS 7",
      status: "enumerated",
      first_seen: "2025-05-04T23:31:00Z",
      last_updated: "2025-05-05T15:43:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-031",
      ip_address: "10.0.0.155",
      hostname: "Internal-host-29",
      os: "CentOS 7",
      status: "enumerated",
      first_seen: "2025-05-01T13:49:00Z",
      last_updated: "2025-05-05T07:33:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-032",
      ip_address: "10.0.0.95",
      hostname: "Internal-host-30",
      os: "CentOS 7",
      status: "exploited",
      first_seen: "2025-05-10T22:35:00Z",
      last_updated: "2025-05-07T19:01:00Z",
      tags: ["internal-lan"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-033",
      ip_address: "192.168.1.7",
      hostname: "DMZ-host-1",
      os: "Ubuntu 20.04",
      status: "enumerated",
      first_seen: "2025-05-08T02:43:00Z",
      last_updated: "2025-05-11T18:06:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-034",
      ip_address: "192.168.1.22",
      hostname: "DMZ-host-2",
      os: "Windows 10 Pro",
      status: "exploited",
      first_seen: "2025-05-10T04:13:00Z",
      last_updated: "2025-05-10T11:35:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-035",
      ip_address: "192.168.1.228",
      hostname: "DMZ-host-3",
      os: "Windows Server 2019",
      status: "exploited",
      first_seen: "2025-05-06T23:58:00Z",
      last_updated: "2025-05-09T12:42:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-036",
      ip_address: "192.168.1.160",
      hostname: "DMZ-host-4",
      os: "Ubuntu 20.04",
      status: "exploited",
      first_seen: "2025-05-03T03:39:00Z",
      last_updated: "2025-05-02T02:00:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-037",
      ip_address: "192.168.1.83",
      hostname: "DMZ-host-5",
      os: "Windows Server 2019",
      status: "exploited",
      first_seen: "2025-05-10T21:20:00Z",
      last_updated: "2025-05-10T02:53:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-038",
      ip_address: "192.168.1.186",
      hostname: "DMZ-host-6",
      os: "Windows 10 Pro",
      status: "vulnerable",
      first_seen: "2025-05-09T20:46:00Z",
      last_updated: "2025-05-06T06:31:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-039",
      ip_address: "192.168.1.118",
      hostname: "DMZ-host-7",
      os: "Windows 10 Pro",
      status: "discovered",
      first_seen: "2025-05-11T07:44:00Z",
      last_updated: "2025-05-11T11:05:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-040",
      ip_address: "192.168.1.52",
      hostname: "DMZ-host-8",
      os: "Ubuntu 20.04",
      status: "exploited",
      first_seen: "2025-05-05T07:35:00Z",
      last_updated: "2025-05-06T21:55:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-041",
      ip_address: "192.168.1.246",
      hostname: "DMZ-host-9",
      os: "CentOS 7",
      status: "exploited",
      first_seen: "2025-05-07T16:08:00Z",
      last_updated: "2025-05-06T01:45:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-042",
      ip_address: "192.168.1.187",
      hostname: "DMZ-host-10",
      os: "CentOS 7",
      status: "vulnerable",
      first_seen: "2025-05-09T17:57:00Z",
      last_updated: "2025-05-08T10:46:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-043",
      ip_address: "192.168.1.89",
      hostname: "DMZ-host-11",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-02T02:04:00Z",
      last_updated: "2025-05-08T04:46:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-044",
      ip_address: "192.168.1.40",
      hostname: "DMZ-host-12",
      os: "Ubuntu 20.04",
      status: "enumerated",
      first_seen: "2025-05-01T22:59:00Z",
      last_updated: "2025-05-04T20:35:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-045",
      ip_address: "192.168.1.110",
      hostname: "DMZ-host-13",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-08T14:25:00Z",
      last_updated: "2025-05-02T05:40:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-046",
      ip_address: "192.168.1.10",
      hostname: "DMZ-host-14",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-12T07:36:00Z",
      last_updated: "2025-05-08T03:56:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-047",
      ip_address: "192.168.1.202",
      hostname: "DMZ-host-15",
      os: "Windows Server 2019",
      status: "discovered",
      first_seen: "2025-05-04T14:48:00Z",
      last_updated: "2025-05-11T06:55:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-048",
      ip_address: "192.168.1.27",
      hostname: "DMZ-host-16",
      os: "Windows 10 Pro",
      status: "exploited",
      first_seen: "2025-05-04T11:47:00Z",
      last_updated: "2025-05-06T12:38:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-049",
      ip_address: "192.168.1.75",
      hostname: "DMZ-host-17",
      os: "Windows 10 Pro",
      status: "exploited",
      first_seen: "2025-05-09T15:46:00Z",
      last_updated: "2025-05-04T16:45:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-050",
      ip_address: "192.168.1.32",
      hostname: "DMZ-host-18",
      os: "Ubuntu 20.04",
      status: "discovered",
      first_seen: "2025-05-06T00:05:00Z",
      last_updated: "2025-05-09T20:04:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-051",
      ip_address: "192.168.1.162",
      hostname: "DMZ-host-19",
      os: "Windows 10 Pro",
      status: "exploited",
      first_seen: "2025-05-01T11:48:00Z",
      last_updated: "2025-05-06T14:41:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-052",
      ip_address: "192.168.1.115",
      hostname: "DMZ-host-20",
      os: "CentOS 7",
      status: "exploited",
      first_seen: "2025-05-06T13:16:00Z",
      last_updated: "2025-05-03T20:31:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-053",
      ip_address: "192.168.1.76",
      hostname: "DMZ-host-21",
      os: "CentOS 7",
      status: "discovered",
      first_seen: "2025-05-02T10:21:00Z",
      last_updated: "2025-05-01T08:14:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-054",
      ip_address: "192.168.1.49",
      hostname: "DMZ-host-22",
      os: "Windows Server 2019",
      status: "vulnerable",
      first_seen: "2025-05-06T05:26:00Z",
      last_updated: "2025-05-10T03:31:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-055",
      ip_address: "192.168.1.29",
      hostname: "DMZ-host-23",
      os: "CentOS 7",
      status: "discovered",
      first_seen: "2025-05-04T06:40:00Z",
      last_updated: "2025-05-07T07:07:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-056",
      ip_address: "192.168.1.98",
      hostname: "DMZ-host-24",
      os: "Windows 10 Pro",
      status: "vulnerable",
      first_seen: "2025-05-05T18:32:00Z",
      last_updated: "2025-05-10T14:14:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-057",
      ip_address: "192.168.1.132",
      hostname: "DMZ-host-25",
      os: "Windows 10 Pro",
      status: "vulnerable",
      first_seen: "2025-05-04T11:18:00Z",
      last_updated: "2025-05-01T13:23:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: ["CVE-2020-0796"],
      notes: [],
    },
    {
      host_id: "host-058",
      ip_address: "192.168.1.231",
      hostname: "DMZ-host-26",
      os: "Ubuntu 20.04",
      status: "enumerated",
      first_seen: "2025-05-01T17:12:00Z",
      last_updated: "2025-05-04T06:07:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-059",
      ip_address: "192.168.1.198",
      hostname: "DMZ-host-27",
      os: "Windows 10 Pro",
      status: "discovered",
      first_seen: "2025-05-03T19:43:00Z",
      last_updated: "2025-05-07T17:43:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-060",
      ip_address: "192.168.1.14",
      hostname: "DMZ-host-28",
      os: "Windows Server 2019",
      status: "enumerated",
      first_seen: "2025-05-10T18:05:00Z",
      last_updated: "2025-05-10T01:24:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 22,
          protocol: "tcp",
          service_name: "ssh",
          product: "OpenSSH",
          version: "8.0",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-061",
      ip_address: "192.168.1.226",
      hostname: "DMZ-host-29",
      os: "CentOS 7",
      status: "vulnerable",
      first_seen: "2025-05-03T04:59:00Z",
      last_updated: "2025-05-05T22:36:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 3389,
          protocol: "tcp",
          service_name: "rdp",
          product: "Microsoft Terminal Services",
          version: "",
          vulnerabilities: [],
        },
        {
          port: 80,
          protocol: "tcp",
          service_name: "http",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
        {
          port: 443,
          protocol: "tcp",
          service_name: "https",
          product: "Apache",
          version: "2.4.41",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
    {
      host_id: "host-062",
      ip_address: "192.168.1.149",
      hostname: "DMZ-host-30",
      os: "Windows Server 2019",
      status: "enumerated",
      first_seen: "2025-05-11T08:30:00Z",
      last_updated: "2025-05-03T20:29:00Z",
      tags: ["dmz"],
      services: [
        {
          port: 445,
          protocol: "tcp",
          service_name: "smb",
          product: "Windows SMB",
          version: "3.0.2",
          vulnerabilities: [],
        },
      ],
      vulnerabilities: [],
      notes: [],
    },
  ],
  exploits: [
    {
      exploit_id: "1d934167-8f0c-4210-ab66-f162141d2cff",
      host_id: "host-004",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-08T06:52:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "2e5c70ae-5c20-40d0-86a4-efb6af4ef311",
      host_id: "host-009",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-10T20:43:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "6dadc4f7-6135-4634-8c84-761a26b4af0f",
      host_id: "host-010",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-07T01:14:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "8f080342-9107-47f8-a47f-15704056fdb1",
      host_id: "host-011",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-06T02:52:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "c24e6573-fc00-4a6e-9d7f-da0edf251a71",
      host_id: "host-018",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-02T20:25:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "aac3a0d7-6367-49ab-94d1-8937cdb9466f",
      host_id: "host-023",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-06T08:07:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "0687163b-1160-4a9d-9c05-1e5b121a8d8d",
      host_id: "host-027",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-04T17:04:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "7b77811c-7c60-4583-8b6c-bba4347719d5",
      host_id: "host-032",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-07T13:27:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "114aeab5-5994-4ded-bbaa-9bbca20e4e8b",
      host_id: "host-034",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-08T22:05:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "13d924de-8c3f-46a4-b536-e118da88052e",
      host_id: "host-035",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-10T17:02:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "a1c8d26e-38ff-46e2-a2f9-5db6b2f3ecce",
      host_id: "host-036",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-02T04:34:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "14b45cad-e7a0-41d4-9968-40d2104b90c8",
      host_id: "host-037",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-03T04:35:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "13e5be6f-6b89-46a6-8c0b-fbd663aebe23",
      host_id: "host-040",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-10T17:33:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "15b737cd-d3d4-416c-8e16-55dedfe84275",
      host_id: "host-041",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-09T10:24:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "0b5d5cc3-e0f3-4b45-983f-273edd6c465b",
      host_id: "host-048",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-09T13:31:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "ff2e4591-f2ca-41f1-865d-b827d466c635",
      host_id: "host-049",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-09T20:22:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "a308bec3-48b4-46e7-91b9-c403bde0c2be",
      host_id: "host-051",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-02T04:19:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
    {
      exploit_id: "3a597f4d-00cc-4d49-9927-c728630bdd95",
      host_id: "host-052",
      type: "RCE",
      tool_used: "autopwn",
      date_executed: "2025-05-04T22:37:00Z",
      result: "shell",
      notes: "Autopwn exploit used.",
    },
  ],
  credentials: [],
  implants: [
    {
      implant_id: "bfcdb41b-ecc9-42a5-b3d3-7d2aa9b0b9ad",
      host_id: "host-004",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-10T11:00:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "01935845-5953-4bef-a30b-ad08d04bbc60",
      host_id: "host-009",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-07T07:53:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "773d3075-8787-46d7-9d7b-d457ab46cb6f",
      host_id: "host-010",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-09T02:38:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "7d7676ec-0316-4b97-bc27-362bd7ed5650",
      host_id: "host-011",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-10T03:14:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "1c51b4a0-9f2f-42f6-a54d-455f18e65840",
      host_id: "host-018",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-01T09:45:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "dc796069-0183-46cf-ad5d-5cdfab5cd65e",
      host_id: "host-023",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-09T22:29:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "9eb6664d-b4a6-4e8c-b619-bb1cfbaeb8b6",
      host_id: "host-027",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-11T16:49:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "331821c5-ed79-4a93-a7e0-f2c63710875c",
      host_id: "host-032",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-06T20:44:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "a69cff11-4a78-4f0c-8dc8-86d0460297d1",
      host_id: "host-034",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-06T09:36:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "52ad292d-8525-4e81-9d7d-4c87776cf79c",
      host_id: "host-035",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-09T04:19:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "b26e0536-f182-4626-9792-6aede8c5980d",
      host_id: "host-036",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-04T13:35:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "a9535c01-1d80-4f38-9c1c-302adcf61136",
      host_id: "host-037",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-05T04:01:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "3a5aee84-53ad-4727-b017-b45ecc9e17d2",
      host_id: "host-040",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-08T21:41:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "d0278870-ab84-4052-aa42-46ee765303d8",
      host_id: "host-041",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-09T11:15:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "21a62601-d1d2-4b28-bdce-075d3f4e1fa9",
      host_id: "host-048",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-02T10:18:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "1715624e-9bd3-429b-aa1d-c5f946be302c",
      host_id: "host-049",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-07T15:16:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "14c06da0-11bd-42bb-b63b-ce4e22742459",
      host_id: "host-051",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-02T01:45:00Z",
      notes: "Reverse shell implant established.",
    },
    {
      implant_id: "a7164970-5ea8-4900-a3eb-2a4ae87f8d07",
      host_id: "host-052",
      implant_type: "reverse-shell",
      user: "SYSTEM",
      privilege: "SYSTEM",
      started_at: "2025-05-03T22:37:00Z",
      notes: "Reverse shell implant established.",
    },
  ],
  network_devices: [
    {
      device_id: "dev-003",
      name: "Internal-device-1",
      device_type: "router",
      ip_addresses: ["10.0.0.157"],
      connected_networks: ["net-001"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-07T14:30:00Z",
      last_updated: "2025-05-11T08:14:00Z",
      notes: "Internal LAN network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-004",
      name: "Internal-device-2",
      device_type: "router",
      ip_addresses: ["10.0.0.150"],
      connected_networks: ["net-001"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-07T15:37:00Z",
      last_updated: "2025-05-02T02:19:00Z",
      notes: "Internal LAN network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-005",
      name: "Internal-device-3",
      device_type: "switch",
      ip_addresses: ["10.0.0.21"],
      connected_networks: ["net-001"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-06T23:19:00Z",
      last_updated: "2025-05-05T18:03:00Z",
      notes: "Internal LAN network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-006",
      name: "Internal-device-4",
      device_type: "router",
      ip_addresses: ["10.0.0.50"],
      connected_networks: ["net-001"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-10T15:08:00Z",
      last_updated: "2025-05-09T19:25:00Z",
      notes: "Internal LAN network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-007",
      name: "Internal-device-5",
      device_type: "firewall",
      ip_addresses: ["10.0.0.8"],
      connected_networks: ["net-001"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-11T21:00:00Z",
      last_updated: "2025-05-09T13:12:00Z",
      notes: "Internal LAN network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-008",
      name: "Internal-device-6",
      device_type: "router",
      ip_addresses: ["10.0.0.223"],
      connected_networks: ["net-001"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-11T05:49:00Z",
      last_updated: "2025-05-10T12:03:00Z",
      notes: "Internal LAN network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-009",
      name: "DMZ-device-1",
      device_type: "router",
      ip_addresses: ["192.168.1.15"],
      connected_networks: ["net-002"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-11T13:29:00Z",
      last_updated: "2025-05-10T03:45:00Z",
      notes: "DMZ network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-010",
      name: "DMZ-device-2",
      device_type: "router",
      ip_addresses: ["192.168.1.168"],
      connected_networks: ["net-002"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-04T11:25:00Z",
      last_updated: "2025-05-01T09:08:00Z",
      notes: "DMZ network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-011",
      name: "DMZ-device-3",
      device_type: "switch",
      ip_addresses: ["192.168.1.68"],
      connected_networks: ["net-002"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-10T23:28:00Z",
      last_updated: "2025-05-05T00:16:00Z",
      notes: "DMZ network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-012",
      name: "DMZ-device-4",
      device_type: "switch",
      ip_addresses: ["192.168.1.165"],
      connected_networks: ["net-002"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-09T07:46:00Z",
      last_updated: "2025-05-03T02:18:00Z",
      notes: "DMZ network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-013",
      name: "DMZ-device-5",
      device_type: "router",
      ip_addresses: ["192.168.1.31"],
      connected_networks: ["net-002"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-01T16:23:00Z",
      last_updated: "2025-05-07T22:28:00Z",
      notes: "DMZ network infrastructure device",
      tags: ["infrastructure"],
    },
    {
      device_id: "dev-014",
      name: "DMZ-device-6",
      device_type: "switch",
      ip_addresses: ["192.168.1.33"],
      connected_networks: ["net-002"],
      credentials: [],
      status: "discovered",
      first_seen: "2025-05-02T23:30:00Z",
      last_updated: "2025-05-05T00:46:00Z",
      notes: "DMZ network infrastructure device",
      tags: ["infrastructure"],
    },
  ],
};
